import ReactQueryProviders from "@/configs/providers/react-query";
import "@/styles/globals.css";
import antdThemeConfig from "@/styles/themes/config";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, theme, Typography } from "antd";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TranslationProvider } from "@/configs/providers/translations";
import { Header } from "antd/es/layout/layout";
import AppHeader from "@/components/ui/header";
import { App as AntdApp } from "antd"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TranslationProvider>
          <AntdApp>
            <AppHeader />
            <ReactQueryProviders>
              <ConfigProvider theme={antdThemeConfig}>
                <AntdRegistry>{children}</AntdRegistry>
              </ConfigProvider>
            </ReactQueryProviders>
          </AntdApp>
        </TranslationProvider>
      </body>
    </html>
  );
}
