import AppHeader from "@/components/ui/header";
import ReactQueryProvider from "@/configs/providers/ReactQueryProvider";
import StoreProvider from "@/configs/providers/StoreProvider";
import { TranslationProvider } from "@/configs/providers/TranslationProvider";
import "@/styles/globals.css";
import antdThemeConfig from "@/styles/themes/config";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { App as AntdApp, ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <StoreProvider>
          <TranslationProvider>
            <AntdApp>
              <AppHeader />
              <ReactQueryProvider>
                <ConfigProvider theme={antdThemeConfig}>
                  <AntdRegistry>{children}</AntdRegistry>
                </ConfigProvider>
              </ReactQueryProvider>
            </AntdApp>
          </TranslationProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
